//login
export const SET_LOGIN_INIT = "SET_LOGIN_INIT";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS"; 
export const SET_LOGIN_FAIL = "SET_LOGIN_FAIL"; 

//logout
export const SET_LOGOUT = "SET_LOGOUT"; 

//user
export const SET_USER_STATE = "SET_USER_STATE";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAIL = "SET_USER_FAIL";

//ent_khoicv
export const SET_ENT_KHOICV_STATE = "SET_ENT_KHOICV_STATE";
export const SET_ENT_KHOICV_SUCCESS = "SET_ENT_KHOICV_SUCCESS";
export const SET_ENT_KHOICV_FAIL = "SET_ENT_KHOICV_FAIL";

//ent_calv
export const SET_ENT_CALV_STATE = "SET_ENT_CALV_STATE";
export const SET_ENT_CALV_SUCCESS = "SET_ENT_CALV_SUCCESS";
export const SET_ENT_CALV_FAIL = "SET_ENT_CALV_FAIL";

//ent_giamsat
export const SET_ENT_GIAMSAT_STATE = "SET_ENT_GIAMSAT_STATE";
export const SET_ENT_GIAMSAT_SUCCESS = "SET_ENT_GIAMSAT_SUCCESS";
export const SET_ENT_GIAMSAT_FAIL = "SET_ENT_GIAMSAT_FAIL";

//ent_khuvuc
export const SET_ENT_TOANHA_STATE = "SET_ENT_TOANHA_STATE";
export const SET_ENT_TOANHA_SUCCESS = "SET_ENT_TOANHA_SUCCESS";
export const SET_ENT_TOANHA_FAIL = "SET_ENT_TOANHA_FAIL";

//ent_khuvuc
export const SET_ENT_KHUVUC_STATE = "SET_ENT_KHUVUC_STATE";
export const SET_ENT_KHUVUC_SUCCESS = "SET_ENT_KHUVUC_SUCCESS";
export const SET_ENT_KHUVUC_FAIL = "SET_ENT_KHUVUC_FAIL";