//login
export const SET_LOGIN_INIT = "SET_LOGIN_INIT";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS"; 
export const SET_LOGIN_FAIL = "SET_LOGIN_FAIL"; 

//logout
export const SET_LOGOUT = "SET_LOGOUT"; 

//user
export const SET_USER_STATE = "SET_USER_STATE";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAIL = "SET_USER_FAIL";

//users
export const SET_ENT_USERS_STATE = "SET_ENT_USERS_STATE";
export const SET_ENT_USERS_SUCCESS = "SET_ENT_USERS_SUCCESS";
export const SET_ENT_USERS_FAIL = "SET_ENT_USERS_FAIL";

//ent_khoicv
export const SET_ENT_KHOICV_STATE = "SET_ENT_KHOICV_STATE";
export const SET_ENT_KHOICV_SUCCESS = "SET_ENT_KHOICV_SUCCESS";
export const SET_ENT_KHOICV_FAIL = "SET_ENT_KHOICV_FAIL";

//ent_calv
export const SET_ENT_CALV_STATE = "SET_ENT_CALV_STATE";
export const SET_ENT_CALV_SUCCESS = "SET_ENT_CALV_SUCCESS";
export const SET_ENT_CALV_FAIL = "SET_ENT_CALV_FAIL";

//ent_toanha
export const SET_ENT_TOANHA_STATE = "SET_ENT_TOANHA_STATE";
export const SET_ENT_TOANHA_SUCCESS = "SET_ENT_TOANHA_SUCCESS";
export const SET_ENT_TOANHA_FAIL = "SET_ENT_TOANHA_FAIL";

//ent_khuvuc
export const SET_ENT_KHUVUC_STATE = "SET_ENT_KHUVUC_STATE";
export const SET_ENT_KHUVUC_SUCCESS = "SET_ENT_KHUVUC_SUCCESS";
export const SET_ENT_KHUVUC_FAIL = "SET_ENT_KHUVUC_FAIL";

//ent_duan
export const SET_ENT_DUAN_STATE = "SET_ENT_DUAN_STATE";
export const SET_ENT_DUAN_SUCCESS = "SET_ENT_DUAN_SUCCESS";
export const SET_ENT_DUAN_FAIL = "SET_ENT_DUAN_FAIL";

//ent_chucvu
export const SET_ENT_CHUCVU_STATE = "SET_ENT_CHUCVU_STATE";
export const SET_ENT_CHUCVU_SUCCESS = "SET_ENT_CHUCVU_SUCCESS";
export const SET_ENT_CHUCVU_FAIL = "SET_ENT_CHUCVU_FAIL";

//ent_checklist
export const SET_ENT_CHECKLIST_STATE = "SET_ENT_CHECKLIST_STATE";
export const SET_ENT_CHECKLIST_SUCCESS = "SET_ENT_CHECKLIST_SUCCESS";
export const SET_ENT_CHECKLIST_FAIL = "SET_ENT_CHECKLIST_FAIL";

//ent_hangmuc
export const SET_ENT_HANGMUC_STATE = "SET_ENT_HANGMUC_STATE";
export const SET_ENT_HANGMUC_SUCCESS = "SET_ENT_HANGMUC_SUCCESS";
export const SET_ENT_HANGMUC_FAIL = "SET_ENT_HANGMUC_FAIL";

//ent_checklist_detail
export const SET_ENT_CHECKLIST_DETAIL_STATE = "SET_ENT_CHECKLIST_DETAIL_STATE";
export const SET_ENT_CHECKLIST_DETAIL_SUCCESS = "SET_ENT_CHECKLIST_DETAIL_SUCCESS";
export const SET_ENT_CHECKLIST_DETAIL_FAIL = "SET_ENT_CHECKLIST_DETAIL_FAIL";

//ent_checklist_detail_return
export const SET_ENT_CHECKLIST_DETAIL_RETURN_STATE = "SET_ENT_CHECKLIST_DETAIL_RETURN_STATE";
export const SET_ENT_CHECKLIST_DETAIL_RETURN_SUCCESS = "SET_ENT_CHECKLIST_DETAIL_RETURN_SUCCESS";
export const SET_ENT_CHECKLIST_DETAIL_RETURN_FAIL = "SET_ENT_CHECKLIST_DETAIL_RETURN_FAIL";

//tb_checklistc
export const SET_TB_CHECKLISTC_STATE = "SET_TB_CHECKLISTC_STATE";
export const SET_TB_CHECKLISTC_SUCCESS = "SET_TB_CHECKLISTC_SUCCESS";
export const SET_TB_CHECKLISTC_FAIL = "SET_TB_CHECKLISTC_FAIL";

//ent_tang
export const SET_ENT_TANG_STATE = "SET_ENT_TANG_STATE";
export const SET_ENT_TANG_SUCCESS = "SET_ENT_TANG_SUCCESS";
export const SET_ENT_TANG_FAIL = "SET_ENT_TANG_FAIL";

export const SET_TB_SUCONGOAI_STATE = "SET_TB_SUCONGOAI_STATE";
export const SET_TB_SUCONGOAI_SUCCESS = "SET_TB_SUCONGOAI_SUCCESS";
export const SET_TB_SUCONGOAI_FAIL = "SET_TB_SUCONGOAI_FAIL";

export const SET_BAOCAOCHISO_STATE = "SET_BAOCAOCHISO_STATE";
export const SET_BAOCAOCHISO_SUCCESS = "SET_BAOCAOCHISO_SUCCESS";
export const SET_BAOCAOCHISO_FAIL = "SET_BAOCAOCHISO_FAIL";
//check_hsse
export const SET_CHECK_HSSE_STATE = "SET_CHECK_HSSE_STATE";
export const SET_CHECK_HSSE_SUCCESS = "SET_CHECK_HSSE_SUCCESS";
export const SET_CHECK_HSSE_FAIL = "SET_CHECK_HSSE_FAIL";

//hsse
export const SET_HSSE_STATE = "SET_HSSE_STATE";
export const SET_HSSE_SUCCESS = "SET_HSSE_SUCCESS";
export const SET_HSSE_FAIL = "SET_HSSE_FAIL";